[[deploy-your-contracts-to-a-public-network]]
= 컨트랙트를 퍼블릭 네트워크로 배포하기

이 가이드는 새로운 OpenZeppelin SDK 프로젝트를 만들고, 로컬 개발 네트워크에서 간단한 `카운터` 컨트랙트를 만든 xref:first.adoc[첫 번째 자습서]를 기반으로합니다. 이제 이 컨트랙트를 공용 네트워크에 배포하는 방법을 살펴 보겠습니다.

다른 공개 테스트 네트워크를 사용할 수도 있지만, 이 자습서에서는 Ropsten 공개 테스트 네트워크를 사용합니다.

NOTE: 이더리움의 테스트 네트워크:
Ropsten (Proof of Work, multi-client, ~ 15 second blocktimes); Rinkeby (Proof of Authority, geth client only, 15 second blocktimes); Kovan (Proof of Authority, parity client only, 4 second blocktimes); Goerli (Proof of Authority, multi-client, 15 second blocktimes)

[[setup]]
== 설정

앞에서 만든 `my-project` 프로젝트 폴더를 사용합니다.

[[test-account]]
== 테스트 계정
우리는 https://github.com/itinance/mnemonics[니모닉]을 사용하여 12 단어 니모닉을 생성합니다. 테스트 목적으로 니모닉을 생성하려면 다음을 실행하십시오.

[source,console]
----
npx mnemonics
----

[[infura]]
== Infura 계정 생성

https://infura.io[Infura]를 사용하여 공개 Ethereum 노드와 상호 작용합니다 (자체 노드를 실행하지 않는 경우). Infura Core는 무료로 사용할 수 있습니다. Infura 웹 사이트의 지시 사항에 따라 새 프로젝트를 등록하고 작성하십시오.

[[install-dotenv]]
== dotenv 설치

https://github.com/motdotla/dotenv[dotenv]를 사용하여 Infura Project ID와 개발 니모닉을 저장합니다. 프로젝트 폴더에서 다음을 실행하여 개발 종속성으로 설치하십시오.

[source,console]
----
$ npm install --save-dev dotenv
----

[[configure-gitignore]]
== .gitignore 구성

.gitignore는 .env (Infura Project ID 및 개발 니모닉)의 값이 실수로 소스 코드 저장소에 커밋되지 않도록 구성합니다. 다음 내용으로 프로젝트 폴더에 .gitignore 파일을 만듭니다.

[source,js]
----
# Dependency directory
node_modules

# local env variables
.env

# truffle build directory
build
----

[[configure-dotenv]]
== `.env` 구성

테스트에 사용되는 Infura Project ID 및 개발 Mnemonic을 저장하도록 `.env`를 구성합니다. Infura Project ID 및 이전에 개발 한 Mnemonic을 사용하여 다음 내용으로 프로젝트 폴더에 `.env` 파일을 작성하십시오.

[source,js]
----
INFURA_PROJECT_ID="ENTER INFURA PROJECT ID"
DEV_MNEMONIC="ENTER 12 WORD SEED PHRASE"
----

[[install-hdwallet-provider]]
== HD Wallet Provider 설치

https://github.com/trufflesuite/truffle/tree/develop/packages/hdwallet-provider[@truffle/hdwallet-provider]를 사용하여 12 또는 24 단어 니모닉에서 파생 된 주소에 대한 거래에 서명합니다. 프로젝트 폴더에서 다음을 실행하여 개발 종속성으로 설치하십시오.

[source,console]
----
$ npm install --save-dev @truffle/hdwallet-provider
----

[[configure-networks-js]]
== `networks.js` 구성

추가 네트워크가 연결되도록 구성하려면 `network.js`를 업데이트하십시오. `dotenv` 및 `@truffle/hdwallet-provider`가 필요하며 Infura Project ID 및 개발 니모닉을 사용하여 네트워크의 제공자를 지정하십시오. `network.js`는 다음과 같아야합니다.

[source,js]
----
require('dotenv').config();

const HDWalletProvider = require('@truffle/hdwallet-provider');
const infuraProjectId = process.env.INFURA_PROJECT_ID;

module.exports = {
  networks: {
    development: {
      protocol: 'http',
      host: 'localhost',
      port: 8545,
      gas: 5000000,
      gasPrice: 5e9,
      networkId: '*',
    },
    ropsten: {
      provider: () => new HDWalletProvider(process.env.DEV_MNEMONIC, "https://ropsten.infura.io/v3/" + infuraProjectId),
      networkId: 3,       // Ropsten's id
    },
    rinkeby: {
      provider: () => new HDWalletProvider(process.env.DEV_MNEMONIC, "https://rinkeby.infura.io/v3/" + infuraProjectId),
      networkId: 4,       // Rinkeby's id
    },
    kovan: {
      provider: () => new HDWalletProvider(process.env.DEV_MNEMONIC, "https://kovan.infura.io/v3/" + infuraProjectId),
      networkId: 42,       // Kovan's id
    },
  },
};
----

NOTE: If you want to use an account other than the first account generated by the mnemonic then you can provide the account index (zero based) as the third parameter to HDWalletProvider. See the truffle tutorial for details: https://www.trufflesuite.com/tutorials/using-infura-custom-provider

NOTE: To expose additional addresses from the same mnemonic set `num_addresses` in your config. 
To change the derivation path to derive addresses set `wallet_hdpath` in your config.
See the https://github.com/trufflesuite/truffle/tree/master/packages/hdwallet-provider[@truffle/hdwallet-provider] repository for details.

[[fund-test-account]]
== Fund test account
Use the interactive command `openzeppelin accounts`, selecting the desired network to view the configured accounts for that network:

[source,console]
----
$ npx openzeppelin accounts
? Pick a network ropsten
Accounts for ropsten:
Default: 0x581f96c12064e2dfb72E8B9722a18731D756Fe73
All:
- 0: 0x581f96c12064e2dfb72E8B9722a18731D756Fe73
----

Add test Ether to the account that you want to use e.g. the default/first account derived from the mnemonic.  You can add funds using a faucet (e.g. https://faucet.ropsten.be).  
If the account doesn’t have enough test Ether when you attempt to deploy, you will get the error `deployment failed with error: insufficient funds for gas * price + value`.

You can also import the 12 word seed phrase into https://metamask.io[MetaMask] and then you can request test Ether from the MetaMask faucet. (https://faucet.metamask.io)  


[[deploy]]
== Deploy contract

We deploy our contract using OpenZeppelin SDK interactive commands by running `openzeppelin create`.  Select the Counter contract, the ropsten network and press N for no to calling a function on the instance after creating it.

[source,console]
----
$ npx openzeppelin create
Nothing to compile, all contracts are up to date.
? Pick a contract to instantiate Counter
? Pick a network ropsten
✓ Contract Counter deployed
All contracts have been deployed
? Call a function to initialize the instance after creating it? No
✓ Setting everything up to create contract instances
✓ Instance created at 0x584Fcb424b17d3505B21c881d57EF9Bf1B18c4A7
0x584Fcb424b17d3505B21c881d57EF9Bf1B18c4A7
----

[[interact]]
== Interact

We can send transactions to our contract using OpenZeppelin SDK interactive commands by running `openzeppelin send-tx`.  Select the Counter contract, the ropsten network, the function to use and an amount to increase the Counter by. e.g. 23.

[source,console]
----
$ npx openzeppelin send-tx
? Pick a network ropsten
? Pick an instance Counter at 0x584Fcb424b17d3505B21c881d57EF9Bf1B18c4A7
? Select which function increase(amount: uint256)
? amount (uint256): 23
✓ Transaction successful. Transaction hash: 0x5f3449b06aee60146ccb3c63d4bdbc8f03bf9140ce9b23b51defe98e32b81a74
----

We can call functions on our contract using OpenZeppelin SDK interactive commands by running `openzeppelin call`.  Select the Counter contract, the ropsten network and the function to call `value()`.

[source,console]
----
$ npx openzeppelin call
? Pick a network ropsten
? Pick an instance Counter at 0x584Fcb424b17d3505B21c881d57EF9Bf1B18c4A7
? Select which function value()
✓ Method 'value()' returned: 23
23
----

[[explorer]]
== View your transactions on a blockchain explorer

You can view your transactions on a blockchain explorer that supports the network you used. For instance, Etherscan supports Ropsten at https://ropsten.etherscan.io/. You can search Etherscan using the contract address of your instance of `Counter`, remember that the contract address is displayed during deployment and when interacting with it (`Instance created at 0x...`).

That's it! You now know how to deploy an OpenZeppelin SDK contract to a public network and interact with it using OpenZeppelin SDK interactive commands.
